openapi: 3.0.0
info:
  version: 2015-06-23
  x-release: v4
  title: 'AWS Device Farm #X Amz Target=DeviceFarm 20150623.CreateDevicePool #X Amz Target=DeviceFarm 20150623.CreateDevicePool #X Amz Target=DeviceFarm 20150623.ListOfferings API'
  description: <p>Welcome to the AWS Device Farm API documentation, which contains APIs for:</p> <ul> <li> <p>Testing on desktop browsers</p> <p> Device Farm makes it possible for you to test your web applications on desktop browsers using Selenium. The APIs for desktop browser testing contain <code>TestGrid</code> in their names. For more information, see <a href="https://docs.aws.amazon.com/devicefarm/latest/testgrid/">Testing Web Applications on Selenium with Device Farm</a>.</p> </li> <li> <p>Testing on real mobile devices</p> <p>Device Farm makes it possible for you to test apps on physical phones, tablets, and other devices in the cloud. For more information, see the <a href="https://docs.aws.amazon.com/devicefarm/latest/developerguide/">Device Farm Developer Guide</a>.</p> </li> </ul>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: devicefarm
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/devicefarm-2015-06-23.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://devicefarm.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Device Farm multi-region endpoint
- url: https://devicefarm.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Device Farm multi-region endpoint
- url: http://devicefarm.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Device Farm endpoint for China (Beijing) and China (Ningxia)
- url: https://devicefarm.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Device Farm endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=DeviceFarm 20150623.ListOfferings'
paths:
  /#X-Amz-Target=DeviceFarm_20150623.ListOfferings:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListOfferings
      description: Returns a list of products or offerings that the user can manage through the API. Each offering record indicates the recurring price per unit and the frequency for that offering. The API returns a <code>NotEligible</code> error if the user is not permitted to invoke the operation. If you must be able to invoke this operation, contact <a href="mailto:aws-devicefarm-support@amazon.com">aws-devicefarm-support@amazon.com</a>.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfferingsResult'
        '480':
          description: ArgumentException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArgumentException'
        '481':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
        '482':
          description: NotEligibleException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotEligibleException'
        '483':
          description: LimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LimitExceededException'
        '484':
          description: ServiceAccountException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceAccountException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListOfferingsRequest'
      parameters:
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - DeviceFarm_20150623.ListOfferings
      tags:
      - '#X Amz Target=DeviceFarm 20150623.ListOfferings'
components:
  schemas:
    DevicePlatform:
      type: string
      enum:
      - ANDROID
      - IOS
    OfferingIdentifier:
      type: string
      minLength: 32
    NotEligibleException: {}
    Message:
      type: string
      minLength: 0
      maxLength: 16384
    PaginationToken:
      type: string
      minLength: 4
      maxLength: 1024
    LimitExceededException: {}
    ListOfferingsResult:
      type: object
      example:
        offerings:
        - type: RECURRING
          description: iOS Unmetered Device Slot
          id: A53D4D73-A6F6-4B82-A0B0-12345EXAMPLE
          platform: IOS
          recurringCharges:
          - cost:
              amount: 250
              currencyCode: USD
            frequency: MONTHLY
        - type: RECURRING
          description: Android Unmetered Device Slot
          id: 8980F81C-00D7-469D-8EC6-12345EXAMPLE
          platform: ANDROID
          recurringCharges:
          - cost:
              amount: 250
              currencyCode: USD
            frequency: MONTHLY
        - type: RECURRING
          description: Android Remote Access Unmetered Device Slot
          id: D68B3C05-1BA6-4360-BC69-12345EXAMPLE
          platform: ANDROID
          recurringCharges:
          - cost:
              amount: 250
              currencyCode: USD
            frequency: MONTHLY
        - type: RECURRING
          description: iOS Remote Access Unmetered Device Slot
          id: 552B4DAD-A6C9-45C4-94FB-12345EXAMPLE
          platform: IOS
          recurringCharges:
          - cost:
              amount: 250
              currencyCode: USD
            frequency: MONTHLY
      properties:
        offerings:
          allOf:
          - $ref: '#/components/schemas/Offerings'
          - description: A value that represents the list offering results.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: An identifier that was returned from the previous call to this operation, which can be used to return the next set of items in the list.
      description: Represents the return values of the list of offerings.
    RecurringChargeFrequency:
      type: string
      enum:
      - MONTHLY
    Offering:
      type: object
      properties:
        id:
          allOf:
          - $ref: '#/components/schemas/OfferingIdentifier'
          - description: The ID that corresponds to a device offering.
        description:
          allOf:
          - $ref: '#/components/schemas/Message'
          - description: A string that describes the offering.
        type:
          allOf:
          - $ref: '#/components/schemas/OfferingType'
          - description: The type of offering (for example, <code>RECURRING</code>) for a device.
        platform:
          allOf:
          - $ref: '#/components/schemas/DevicePlatform'
          - description: The platform of the device (for example, <code>ANDROID</code> or <code>IOS</code>).
        recurringCharges:
          allOf:
          - $ref: '#/components/schemas/RecurringCharges'
          - description: Specifies whether there are recurring charges for the offering.
      description: Represents the metadata of a device offering.
    OfferingType:
      type: string
      enum:
      - RECURRING
    ListOfferingsRequest:
      type: object
      title: ListOfferingsRequest
      properties:
        nextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: An identifier that was returned from the previous call to this operation, which can be used to return the next set of items in the list.
      description: Represents the request to list all offerings.
    RecurringCharge:
      type: object
      properties:
        cost:
          allOf:
          - $ref: '#/components/schemas/MonetaryAmount'
          - description: The cost of the recurring charge.
        frequency:
          allOf:
          - $ref: '#/components/schemas/RecurringChargeFrequency'
          - description: The frequency in which charges recur.
      description: Specifies whether charges for devices are recurring.
    CurrencyCode:
      type: string
      enum:
      - USD
    Offerings:
      type: array
      items:
        $ref: '#/components/schemas/Offering'
    ServiceAccountException: {}
    NotFoundException: {}
    MonetaryAmount:
      type: object
      properties:
        amount:
          allOf:
          - $ref: '#/components/schemas/Double'
          - description: The numerical amount of an offering or transaction.
        currencyCode:
          allOf:
          - $ref: '#/components/schemas/CurrencyCode'
          - description: The currency code of a monetary amount. For example, <code>USD</code> means U.S. dollars.
      description: A number that represents the monetary amount for an offering or transaction.
    Double:
      type: number
      format: double
    RecurringCharges:
      type: array
      items:
        $ref: '#/components/schemas/RecurringCharge'
    ArgumentException: {}
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/devicefarm/
x-hasEquivalentPaths: true
