openapi: 3.0.0
info:
  version: 2015-06-23
  x-release: v4
  title: 'AWS Device Farm #X Amz Target=DeviceFarm 20150623.CreateDevicePool #X Amz Target=DeviceFarm 20150623.CreateDevicePool #X Amz Target=DeviceFarm 20150623.GetTest API'
  description: <p>Welcome to the AWS Device Farm API documentation, which contains APIs for:</p> <ul> <li> <p>Testing on desktop browsers</p> <p> Device Farm makes it possible for you to test your web applications on desktop browsers using Selenium. The APIs for desktop browser testing contain <code>TestGrid</code> in their names. For more information, see <a href="https://docs.aws.amazon.com/devicefarm/latest/testgrid/">Testing Web Applications on Selenium with Device Farm</a>.</p> </li> <li> <p>Testing on real mobile devices</p> <p>Device Farm makes it possible for you to test apps on physical phones, tablets, and other devices in the cloud. For more information, see the <a href="https://docs.aws.amazon.com/devicefarm/latest/developerguide/">Device Farm Developer Guide</a>.</p> </li> </ul>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: devicefarm
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/devicefarm-2015-06-23.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://devicefarm.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Device Farm multi-region endpoint
- url: https://devicefarm.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Device Farm multi-region endpoint
- url: http://devicefarm.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Device Farm endpoint for China (Beijing) and China (Ningxia)
- url: https://devicefarm.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Device Farm endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=DeviceFarm 20150623.GetTest'
paths:
  /#X-Amz-Target=DeviceFarm_20150623.GetTest:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetTest
      description: Gets information about a test.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTestResult'
        '480':
          description: ArgumentException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArgumentException'
        '481':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
        '482':
          description: LimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LimitExceededException'
        '483':
          description: ServiceAccountException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceAccountException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetTestRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - DeviceFarm_20150623.GetTest
      tags:
      - '#X Amz Target=DeviceFarm 20150623.GetTest'
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  schemas:
    Integer:
      type: integer
    DeviceMinutes:
      type: object
      properties:
        total:
          allOf:
          - $ref: '#/components/schemas/Double'
          - description: When specified, represents the total minutes used by the resource to run tests.
        metered:
          allOf:
          - $ref: '#/components/schemas/Double'
          - description: When specified, represents only the sum of metered minutes used by the resource to run tests.
        unmetered:
          allOf:
          - $ref: '#/components/schemas/Double'
          - description: When specified, represents only the sum of unmetered minutes used by the resource to run tests.
      description: Represents the total (metered or unmetered) minutes used by the resource to run tests. Contains the sum of minutes consumed by all children.
    Test:
      type: object
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/AmazonResourceName'
          - description: The test's ARN.
        name:
          allOf:
          - $ref: '#/components/schemas/Name'
          - description: The test's name.
        type:
          allOf:
          - $ref: '#/components/schemas/TestType'
          - description: <p>The test's type.</p> <p>Must be one of the following values:</p> <ul> <li> <p>BUILTIN_FUZZ</p> </li> <li> <p>BUILTIN_EXPLORER</p> <note> <p>For Android, an app explorer that traverses an Android app, interacting with it and capturing screenshots at the same time.</p> </note> </li> <li> <p>APPIUM_JAVA_JUNIT</p> </li> <li> <p>APPIUM_JAVA_TESTNG</p> </li> <li> <p>APPIUM_PYTHON</p> </li> <li> <p>APPIUM_NODE</p> </li> <li> <p>APPIUM_RUBY</p> </li> <li> <p>APPIUM_WEB_JAVA_JUNIT</p> </li> <li> <p>APPIUM_WEB_JAVA_TESTNG</p> </li> <li> <p>APPIUM_WEB_PYTHON</p> </li> <li> <p>APPIUM_WEB_NODE</p> </li> <li> <p>APPIUM_WEB_RUBY</p> </li> <li> <p>CALABASH</p> </li> <li> <p>INSTRUMENTATION</p> </li> <li> <p>UIAUTOMATION</p> </li> <li> <p>UIAUTOMATOR</p> </li> <li> <p>XCTEST</p> </li> <li> <p>XCTEST_UI</p> </li> </ul>
        created:
          allOf:
          - $ref: '#/components/schemas/DateTime'
          - description: When the test was created.
        status:
          allOf:
          - $ref: '#/components/schemas/ExecutionStatus'
          - description: <p>The test's status.</p> <p>Allowed values include:</p> <ul> <li> <p>PENDING</p> </li> <li> <p>PENDING_CONCURRENCY</p> </li> <li> <p>PENDING_DEVICE</p> </li> <li> <p>PROCESSING</p> </li> <li> <p>SCHEDULING</p> </li> <li> <p>PREPARING</p> </li> <li> <p>RUNNING</p> </li> <li> <p>COMPLETED</p> </li> <li> <p>STOPPING</p> </li> </ul>
        result:
          allOf:
          - $ref: '#/components/schemas/ExecutionResult'
          - description: <p>The test's result.</p> <p>Allowed values include:</p> <ul> <li> <p>PENDING</p> </li> <li> <p>PASSED</p> </li> <li> <p>WARNED</p> </li> <li> <p>FAILED</p> </li> <li> <p>SKIPPED</p> </li> <li> <p>ERRORED</p> </li> <li> <p>STOPPED</p> </li> </ul>
        started:
          allOf:
          - $ref: '#/components/schemas/DateTime'
          - description: The test's start time.
        stopped:
          allOf:
          - $ref: '#/components/schemas/DateTime'
          - description: The test's stop time.
        counters:
          allOf:
          - $ref: '#/components/schemas/Counters'
          - description: The test's result counters.
        message:
          allOf:
          - $ref: '#/components/schemas/Message'
          - description: A message about the test's result.
        deviceMinutes:
          allOf:
          - $ref: '#/components/schemas/DeviceMinutes'
          - description: Represents the total (metered or unmetered) minutes used by the test.
      description: Represents a condition that is evaluated.
    Message:
      type: string
      minLength: 0
      maxLength: 16384
    LimitExceededException: {}
    DateTime:
      type: string
      format: date-time
    ExecutionResult:
      type: string
      enum:
      - PENDING
      - PASSED
      - WARNED
      - FAILED
      - SKIPPED
      - ERRORED
      - STOPPED
    Counters:
      type: object
      properties:
        total:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The total number of entities.
        passed:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The number of passed entities.
        failed:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The number of failed entities.
        warned:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The number of warned entities.
        errored:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The number of errored entities.
        stopped:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The number of stopped entities.
        skipped:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The number of skipped entities.
      description: Represents entity counters.
    GetTestResult:
      type: object
      example:
        test: {}
      properties:
        test:
          allOf:
          - $ref: '#/components/schemas/Test'
          - description: A test condition that is evaluated.
      description: Represents the result of a get test request.
    ExecutionStatus:
      type: string
      enum:
      - PENDING
      - PENDING_CONCURRENCY
      - PENDING_DEVICE
      - PROCESSING
      - SCHEDULING
      - PREPARING
      - RUNNING
      - COMPLETED
      - STOPPING
    TestType:
      type: string
      enum:
      - BUILTIN_FUZZ
      - BUILTIN_EXPLORER
      - WEB_PERFORMANCE_PROFILE
      - APPIUM_JAVA_JUNIT
      - APPIUM_JAVA_TESTNG
      - APPIUM_PYTHON
      - APPIUM_NODE
      - APPIUM_RUBY
      - APPIUM_WEB_JAVA_JUNIT
      - APPIUM_WEB_JAVA_TESTNG
      - APPIUM_WEB_PYTHON
      - APPIUM_WEB_NODE
      - APPIUM_WEB_RUBY
      - CALABASH
      - INSTRUMENTATION
      - UIAUTOMATION
      - UIAUTOMATOR
      - XCTEST
      - XCTEST_UI
      - REMOTE_ACCESS_RECORD
      - REMOTE_ACCESS_REPLAY
    ServiceAccountException: {}
    NotFoundException: {}
    AmazonResourceName:
      type: string
      pattern: ^arn:.+
      minLength: 32
      maxLength: 1011
    Double:
      type: number
      format: double
    GetTestRequest:
      type: object
      required:
      - arn
      title: GetTestRequest
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/AmazonResourceName'
          - description: The test's ARN.
      description: Represents a request to the get test operation.
    Name:
      type: string
      minLength: 0
      maxLength: 256
    ArgumentException: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/devicefarm/
x-hasEquivalentPaths: true
